# Generated by Django 5.0.6 on 2024-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_f_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='unzipped_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
